"""Create the SQLite database and load the demo catalogue.

Run from the backend directory:

    python -m database.seed

Re-running replaces the catalogue; the table is rewritten from scratch.
"""

from __future__ import annotations

import json
import sqlite3

from database.db import connect, get_db_path, init_schema

PACKAGES: list[dict[str, object]] = [
    {
        "id": 1,
        "name": "Paradise Beach Package",
        "destination": "Maragogi",
        "country": "Brazil",
        "category": "beach",
        "description": "Natural pools, warm water and all-inclusive resorts on the Alagoas coast.",
        "days": 7,
        "price": 3500.0,
        "max_people": 4,
        "best_months": ['December', 'January', 'February'],
    },
    {
        "id": 2,
        "name": "Gramado Winter Experience",
        "destination": "Gramado",
        "country": "Brazil",
        "category": "cold",
        "description": "Mountain town with chocolate shops, fondue and the Natal Luz festival.",
        "days": 5,
        "price": 2800.0,
        "max_people": 4,
        "best_months": ['June', 'July'],
    },
    {
        "id": 3,
        "name": "Natal Beach Holiday",
        "destination": "Natal",
        "country": "Brazil",
        "category": "beach",
        "description": "Dunes, buggy rides and calm beaches along the Rio Grande do Norte shore.",
        "days": 6,
        "price": 4200.0,
        "max_people": 4,
        "best_months": ['December', 'January'],
    },
    {
        "id": 4,
        "name": "Rio Highlights City Break",
        "destination": "Rio de Janeiro",
        "country": "Brazil",
        "category": "city",
        "description": "Christ the Redeemer, Sugarloaf and Copacabana in a compact long weekend.",
        "days": 4,
        "price": 2400.0,
        "max_people": 4,
        "best_months": ['March', 'April', 'September', 'October'],
    },
    {
        "id": 5,
        "name": "Chapada Diamantina Trekking",
        "destination": "Chapada Diamantina",
        "country": "Brazil",
        "category": "adventure",
        "description": "Guided treks to waterfalls, caves and plateau viewpoints in Bahia.",
        "days": 8,
        "price": 5200.0,
        "max_people": 6,
        "best_months": ['May', 'June', 'July', 'August'],
    },
    {
        "id": 6,
        "name": "Ouro Preto Colonial Route",
        "destination": "Ouro Preto",
        "country": "Brazil",
        "category": "culture",
        "description": "Baroque churches, cobbled streets and mining history in Minas Gerais.",
        "days": 4,
        "price": 1900.0,
        "max_people": 4,
        "best_months": ['April', 'May', 'September'],
    },
    {
        "id": 7,
        "name": "Amazon River Expedition",
        "destination": "Manaus",
        "country": "Brazil",
        "category": "nature",
        "description": "Riverboat lodging, igarape canoeing and wildlife spotting in the rainforest.",
        "days": 6,
        "price": 6800.0,
        "max_people": 8,
        "best_months": ['July', 'August', 'September'],
    },
    {
        "id": 8,
        "name": "Fernando de Noronha Escape",
        "destination": "Fernando de Noronha",
        "country": "Brazil",
        "category": "beach",
        "description": "Protected marine park with diving, snorkelling and near-empty beaches.",
        "days": 5,
        "price": 9800.0,
        "max_people": 2,
        "best_months": ['September', 'October', 'November'],
    },
    {
        "id": 9,
        "name": "Bonito Freshwater Adventure",
        "destination": "Bonito",
        "country": "Brazil",
        "category": "nature",
        "description": "Snorkelling in crystal-clear rivers, caves and waterfalls in Mato Grosso do Sul.",
        "days": 5,
        "price": 4600.0,
        "max_people": 6,
        "best_months": ['March', 'April', 'May', 'September'],
    },
    {
        "id": 10,
        "name": "Salvador Historic Coast",
        "destination": "Salvador",
        "country": "Brazil",
        "category": "culture",
        "description": "Pelourinho, Afro-Brazilian heritage and beaches on the Bahia coastline.",
        "days": 5,
        "price": 3200.0,
        "max_people": 4,
        "best_months": ['December', 'January', 'February'],
    },
    {
        "id": 11,
        "name": "Sao Paulo Gastronomy Weekend",
        "destination": "Sao Paulo",
        "country": "Brazil",
        "category": "city",
        "description": "Restaurants, museums and nightlife in the largest city in the country.",
        "days": 3,
        "price": 1800.0,
        "max_people": 4,
        "best_months": ['April', 'May', 'September', 'October'],
    },
    {
        "id": 12,
        "name": "Serra Catarinense Snow Chase",
        "destination": "Urubici",
        "country": "Brazil",
        "category": "cold",
        "description": "Highest towns in southern Brazil, canyons and the rare chance of snow.",
        "days": 4,
        "price": 2600.0,
        "max_people": 4,
        "best_months": ['June', 'July', 'August'],
    },
    {
        "id": 13,
        "name": "Rome Eternal City",
        "destination": "Rome",
        "country": "Italy",
        "category": "culture",
        "description": "Colosseum, Vatican Museums and Trastevere dinners with a local guide.",
        "days": 7,
        "price": 18500.0,
        "max_people": 2,
        "best_months": ['April', 'May', 'September', 'October'],
    },
    {
        "id": 14,
        "name": "Amalfi Coast Escape",
        "destination": "Amalfi Coast",
        "country": "Italy",
        "category": "beach",
        "description": "Cliffside villages, Positano beaches and boat days along the Tyrrhenian.",
        "days": 8,
        "price": 24000.0,
        "max_people": 2,
        "best_months": ['May', 'June', 'July', 'August', 'September'],
    },
    {
        "id": 15,
        "name": "Tuscany Vineyards and Hills",
        "destination": "Tuscany",
        "country": "Italy",
        "category": "nature",
        "description": "Chianti wineries, cypress roads and slow days between Siena and Florence.",
        "days": 9,
        "price": 22000.0,
        "max_people": 4,
        "best_months": ['May', 'June', 'September', 'October'],
    },
    {
        "id": 16,
        "name": "Venice and the Lagoon",
        "destination": "Venice",
        "country": "Italy",
        "category": "city",
        "description": "Canals, Murano glass workshops and the Biennale when it is running.",
        "days": 5,
        "price": 16000.0,
        "max_people": 2,
        "best_months": ['April', 'May', 'September', 'October'],
    },
    {
        "id": 17,
        "name": "Dolomites Winter Week",
        "destination": "Dolomites",
        "country": "Italy",
        "category": "cold",
        "description": "Ski-in chalets, via ferrata trails and alpine refuges in South Tyrol.",
        "days": 7,
        "price": 21000.0,
        "max_people": 4,
        "best_months": ['January', 'February', 'March'],
    },
    {
        "id": 18,
        "name": "Lisbon and Sintra",
        "destination": "Lisbon",
        "country": "Portugal",
        "category": "city",
        "description": "Miradouros, pasteis de nata and a day trip to the palaces of Sintra.",
        "days": 6,
        "price": 14500.0,
        "max_people": 4,
        "best_months": ['April', 'May', 'September', 'October'],
    },
    {
        "id": 19,
        "name": "Douro Valley Wine Cruise",
        "destination": "Douro Valley",
        "country": "Portugal",
        "category": "nature",
        "description": "Terraced vineyards, port houses and a slow boat up the Douro river.",
        "days": 7,
        "price": 17800.0,
        "max_people": 2,
        "best_months": ['May', 'June', 'September', 'October'],
    },
    {
        "id": 20,
        "name": "Algarve Beach Week",
        "destination": "Algarve",
        "country": "Portugal",
        "category": "beach",
        "description": "Golden cliffs, sea caves and quiet coves on the southern Portuguese coast.",
        "days": 7,
        "price": 15200.0,
        "max_people": 4,
        "best_months": ['May', 'June', 'July', 'August', 'September'],
    },
    {
        "id": 21,
        "name": "Barcelona and Costa Brava",
        "destination": "Barcelona",
        "country": "Spain",
        "category": "city",
        "description": "Gaudi architecture, tapas crawls and beach days north of the city.",
        "days": 6,
        "price": 15800.0,
        "max_people": 4,
        "best_months": ['May', 'June', 'July', 'August', 'September'],
    },
    {
        "id": 22,
        "name": "Andalusia Moorish Route",
        "destination": "Seville",
        "country": "Spain",
        "category": "culture",
        "description": "Alhambra, Cordoba mosque-cathedral and flamenco in Seville.",
        "days": 8,
        "price": 17500.0,
        "max_people": 4,
        "best_months": ['March', 'April', 'May', 'October'],
    },
    {
        "id": 23,
        "name": "Paris Classic Week",
        "destination": "Paris",
        "country": "France",
        "category": "city",
        "description": "Louvre, Montmartre, Seine walks and a day at Versailles.",
        "days": 6,
        "price": 19000.0,
        "max_people": 2,
        "best_months": ['April', 'May', 'September', 'October'],
    },
    {
        "id": 24,
        "name": "French Alps Ski Trip",
        "destination": "Chamonix",
        "country": "France",
        "category": "cold",
        "description": "Mont Blanc slopes, mountain huts and long lift-served descents.",
        "days": 7,
        "price": 23500.0,
        "max_people": 4,
        "best_months": ['January', 'February', 'March'],
    },
    {
        "id": 25,
        "name": "Provence Lavender Roads",
        "destination": "Provence",
        "country": "France",
        "category": "nature",
        "description": "Lavender fields in bloom, hilltop villages and Marseille markets.",
        "days": 7,
        "price": 20500.0,
        "max_people": 4,
        "best_months": ['June', 'July'],
    },
    {
        "id": 26,
        "name": "Japan Cherry Blossom Circuit",
        "destination": "Kyoto",
        "country": "Japan",
        "category": "culture",
        "description": "Temples, gardens and hanami season between Kyoto, Nara and Tokyo.",
        "days": 10,
        "price": 32000.0,
        "max_people": 2,
        "best_months": ['March', 'April'],
    },
    {
        "id": 27,
        "name": "Tokyo Neon Week",
        "destination": "Tokyo",
        "country": "Japan",
        "category": "city",
        "description": "Shibuya, izakaya nights, day trips to Hakone and Mount Fuji views.",
        "days": 8,
        "price": 28000.0,
        "max_people": 2,
        "best_months": ['April', 'May', 'October', 'November'],
    },
    {
        "id": 28,
        "name": "Patagonia Trekking Circuit",
        "destination": "Torres del Paine",
        "country": "Chile",
        "category": "adventure",
        "description": "W-trek through granite towers, glaciers and turquoise lakes.",
        "days": 10,
        "price": 26500.0,
        "max_people": 6,
        "best_months": ['December', 'January', 'February'],
    },
    {
        "id": 29,
        "name": "Atacama Desert Stargazing",
        "destination": "Atacama",
        "country": "Chile",
        "category": "nature",
        "description": "Salt flats, geysers at dawn and some of the clearest night skies on earth.",
        "days": 6,
        "price": 14000.0,
        "max_people": 4,
        "best_months": ['April', 'May', 'September', 'October'],
    },
    {
        "id": 30,
        "name": "Bariloche Snow Week",
        "destination": "Bariloche",
        "country": "Argentina",
        "category": "cold",
        "description": "Ski slopes on Cerro Catedral plus lakeside chalets in Patagonia.",
        "days": 7,
        "price": 7400.0,
        "max_people": 4,
        "best_months": ['June', 'July', 'August'],
    },
    {
        "id": 31,
        "name": "Buenos Aires Tango Weekend",
        "destination": "Buenos Aires",
        "country": "Argentina",
        "category": "city",
        "description": "Steakhouses, San Telmo markets and a tango show in the Argentine capital.",
        "days": 4,
        "price": 3100.0,
        "max_people": 4,
        "best_months": ['March', 'April', 'October', 'November'],
    },
    {
        "id": 32,
        "name": "Cusco and Machu Picchu Trail",
        "destination": "Cusco",
        "country": "Peru",
        "category": "culture",
        "description": "Inca ruins, the Sacred Valley and a guided visit to Machu Picchu.",
        "days": 9,
        "price": 8600.0,
        "max_people": 6,
        "best_months": ['May', 'June', 'July', 'August'],
    },
    {
        "id": 33,
        "name": "Inca Jungle Adventure",
        "destination": "Cusco",
        "country": "Peru",
        "category": "adventure",
        "description": "Biking, rafting and jungle trekking on the alternative route to Machu Picchu.",
        "days": 7,
        "price": 9200.0,
        "max_people": 6,
        "best_months": ['May', 'June', 'July', 'August'],
    },
    {
        "id": 34,
        "name": "New York City Break",
        "destination": "New York",
        "country": "United States",
        "category": "city",
        "description": "Museums, Broadway and Central Park in every season.",
        "days": 6,
        "price": 21000.0,
        "max_people": 4,
        "best_months": ['April', 'May', 'September', 'October', 'December'],
    },
    {
        "id": 35,
        "name": "Utah National Parks Road Trip",
        "destination": "Moab",
        "country": "United States",
        "category": "adventure",
        "description": "Arches, Canyonlands and slot canyons on a self-drive desert loop.",
        "days": 9,
        "price": 24500.0,
        "max_people": 4,
        "best_months": ['April', 'May', 'September', 'October'],
    },
]

_COLUMNS = (
    "id",
    "name",
    "destination",
    "country",
    "category",
    "description",
    "days",
    "price",
    "max_people",
    "best_months",
)


def seed(connection: sqlite3.Connection) -> int:
    init_schema(connection)
    connection.execute("DELETE FROM travel_packages")
    connection.executemany(
        f"INSERT INTO travel_packages ({', '.join(_COLUMNS)}) "
        f"VALUES ({', '.join('?' for _ in _COLUMNS)})",
        [
            tuple(
                json.dumps(package[column])
                if column == "best_months"
                else package[column]
                for column in _COLUMNS
            )
            for package in PACKAGES
        ],
    )
    connection.commit()
    return len(PACKAGES)


def main() -> None:
    connection = connect()
    try:
        count = seed(connection)
    finally:
        connection.close()
    print(f"Seeded {count} travel packages into {get_db_path()}")


if __name__ == "__main__":
    main()
